### PR TITLE
Updated pom structure and artifactId so GAV format is followed

### PR DESCRIPTION
**Pull request by tobiasake**
### Applicable Issues
Follow common GAV format that all Eiffel components follow.

### Description of the Change
Today eiffel-remrem-generate application is released with war artifact ArtifactID "generate-service" which do not follow GAV format where the Eiffel application name should be the used as artifactId, as other Eiffel components is following.

This change the artifactId to use the "eiffel-remrem-generate" application name instead of "generate-service" name.

This change makes also so that JitPack stores with correct artifact name and version and path.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by:

### CODE REVIEW

**Comment by raja-maragani** [comment]
@tobiasake this change will impact the our internal CI/CD flows, we need to add a new internal task to handle this,
@SantoshNC68 please create new task.

**Comment by tobiasake** [comment]
> @tobiasake this change will impact the our internal CI/CD flows, we need to add a new internal task to handle this,
> @SantoshNC68 please create new task.

Ok, we can skip this GAV/purl change , but check the Ericsson internal CIC ticket about this and other internal tasks in CIC ticket for handling RemRem CI/CD internally at Ericsson.

**Comment by SantoshNC68** [comment]
I think this change needs to be discussed and not so important, as there is an internal ticket we can have discussion first there and can create the PR if needed. @tobiasake can you close this PR until the CIC discussion is done ?

**Comment by tobiasake** [comment]
Closing this PR since it will not be accepted for the moment.

**Pull request closed without merging**
