### PR TITLE
Make virtual host used for RabbitMQ connections configurable

### PR DESCRIPTION
**Pull request by devkonarev**
## Applicable Issues
#175 

### Description of the Change
There is no configuration option for which RabbitMQ virtualhost to connect to. Connections will always be made to the default virtualhost, "/". Just like we can configure the hostname, port, use of TLS, username, and password we should be able to configure the virtualhost.

### Alternate Designs

N/A

### Benefits

Virtualhosts are frequently used for multi-tenancy or to separate production environments and test environments. Any RabbitMQ client should be able to connect to any available virtualhost.

### Possible Drawbacks

None

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Denis Konarev <35542883+devkonarev@users.noreply.github.com>

### CODE REVIEW

**Comment by devkonarev** [comment]
Thanks for the approval. Merge conflicts have now been resolved.

**Comment by magnusbaeck** [comment]
@devkonarev, thanks for making this change! I was just about to implement it myself. Unfortunately there's still a merge conflict before this change can be merged. For some reason your PR wasn't merged earlier after the approvals were in and a subsequent commit created a conflict. It should be trivial to resolve though. Would you mind having a look at it?

**Comment by devkonarev** [comment]
@magnusbaeck sure, I will take a look.

**Comment by devkonarev** [comment]
Merge conflicts have been resolved.

**Comment by magnusbaeck** [comment]
@SantoshNC68 and @e-pettersson-ericsson, could you please merge this PR, close the issue and, if it's not too much trouble, make a new release?

**Comment by SantoshNC68** [comment]
> @SantoshNC68 and @e-pettersson-ericsson, could you please merge this PR, close the issue and, if it's not too much trouble, make a new release?

I will merge them.. for the release sure I will check if we are awaiting anything else for a release otherwise I will do it

**Pull request merged**
